# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# ~/.config/zsh/zshrc
#
#░▀▀█░█▀▀░█░█░█▀▄░█▀▀
#░▄▀░░▀▀█░█▀█░█▀▄░█░░
#░▀▀▀░▀▀▀░▀░▀░▀░▀░▀▀▀


### Theme
# Pywal color scheme in new terminals
# $HOME/.local/bin/wal -qRe

zmodload zsh/zprof
### Antigen
# Load antigen
antigen_path=$HOME/.local/share/antigen.zsh

if [[ ! -f $antigen_path ]]; then
    echo "[+] Downloading Antigen"
    mkdir ~/.local/share/
    curl -sL git.io/antigen -o $antigen_path &&
	echo "[$] Downloaded successfully"
fi

source $HOME/.local/share/antigen.zsh

# Set up antigen
antigen use oh-my-zsh
antigen theme romkatv/powerlevel10k

# Antigen bundles
antigen bundle git
antigen bundle pip
antigen bundle tperich/auto-ls
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle MichaelAquilina/zsh-you-should-use
antigen apply

# Auto-ls config
if command -v lsd > /dev/null; then
    AUTO_LS_COMMANDS=(lsd) AUTO_LS_NEWLINE=false 
else
    AUTO_LS_COMMANDS=(ls) AUTO_LS_NEWLINE=false 
fi

# Load autojump
autojump_path="/usr/share/autojump/autojump.zsh"
[ -f $autojump_path ] && source $autojump_path

# Load fzf keybinds
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

### Source
# Custom aliases
source $ZDOTDIR/aliases.zsh

# Custom functions
source $ZDOTDIR/helpers.zsh

# Install missing stuff
source $ZDOTDIR/installers.zsh

# To customize prompt, run `p10k configure` or edit $ZDOTDIR/p10k.zsh.
[[ -f $ZDOTDIR/p10k.zsh ]] && source $ZDOTDIR/p10k.zsh

# PATH="/home/demon/perl5/bin${PATH:+:${PATH}}"; export PATH;
# PERL5LIB="/home/demon/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
# PERL_LOCAL_LIB_ROOT="/home/demon/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
# PERL_MB_OPT="--install_base \"/home/demon/perl5\""; export PERL_MB_OPT;
# PERL_MM_OPT="INSTALL_BASE=/home/demon/perl5"; export PERL_MM_OPT;

export NVM_DIR="$HOME/.nvm"
export N_PREFIX="$HOME/.node_versions"
export PATH="$PATH:$HOME/.node_versions/bin"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
