# ~/.config/zsh/zshrc
#
#░▀▀█░█▀▀░█░█░█▀▄░█▀▀
#░▄▀░░▀▀█░█▀█░█▀▄░█░░
#░▀▀▀░▀▀▀░▀░▀░▀░▀░▀▀▀


### Theme
# Pywal color scheme in new terminals
# $HOME/.local/bin/wal -qRe

zmodload zsh/zprof
### Antigen
# Load antigen
antigen_path=$HOME/.local/share/antigen.zsh

if [[ ! -f $antigen_path ]]; then
    echo "[+] Downloading Antigen"
    curl -sL git.io/antigen -o $antigen_path &&
	echo "[$] Downloaded successfully"
fi

source $HOME/.local/share/antigen.zsh

# Set up antigen
antigen use oh-my-zsh
antigen theme romkatv/powerlevel10k

# Antigen bundles
antigen bundle git
antigen bundle pip
antigen bundle tperich/auto-ls
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle MichaelAquilina/zsh-you-should-use
antigen apply

# Auto-ls config
if command -v lsd > /dev/null; then
    AUTO_LS_COMMANDS=(lsd) AUTO_LS_NEWLINE=false 
else
    AUTO_LS_COMMANDS=(ls) AUTO_LS_NEWLINE=false 
fi

# Load autojump
autojump_path="/usr/share/autojump/autojump.zsh"
[ -f $autojump_path ] && source $autojump_path

# Load fzf keybinds
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

### Source
# Custom aliases
source $ZDOTDIR/aliases.zsh

# Custom functions
source $ZDOTDIR/helpers.zsh

# Install missing stuff
source $ZDOTDIR/installers.zsh

# To customize prompt, run `p10k configure` or edit $ZDOTDIR/p10k.zsh.
[[ -f $ZDOTDIR/p10k.zsh ]] && source $ZDOTDIR/p10k.zsh

if compaudit > /dev/null | grep "/"; then
    echo "Fixing insecure directories..."
    chmod g-w $(compaudit | tail -n +2)
fi

# PATH="/home/demon/perl5/bin${PATH:+:${PATH}}"; export PATH;
# PERL5LIB="/home/demon/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
# PERL_LOCAL_LIB_ROOT="/home/demon/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
# PERL_MB_OPT="--install_base \"/home/demon/perl5\""; export PERL_MB_OPT;
# PERL_MM_OPT="INSTALL_BASE=/home/demon/perl5"; export PERL_MM_OPT;
